### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Amerlander** [svelteness/kit-docs#13]
It would be great to be able to change the default text strings to be able to translate them.

As far as I see, there are these static strings:

Title of the Buttons on the Bottom:
- "Next"
- "Previous"

Title of the right Sidebar:
- "On this page"

Options on the Theme toggle:
- "Light"
- "Dark"
- "System"

Titles on the admonitions:
- "Note"
- "Info"
- "Tip"
- "Warning"
- "Danger"
- "Experimental"

Search (?):
- "Search Documentation"
- "No recent searches"
- "to select"
- "to navigate"
- "to close"
- "Search by"

**Comment by mihar-22** [comment]
Thank you for documenting it all for me, super helpful. I'll create an `i18n` field on `KitDocsLayout` now and translate all mentioned strings. I'm not sure we can change Algolia search text? I'll look at the docs.

**Comment by mihar-22** [comment]
Added this option in, feel free to test it out and let me know how you go. 

[Docs Link](https://kit-docs.svelteness.dev/docs/default-layout/configuration#language-i18n)
[Translations Link](https://github.com/svelteness/kit-docs/blob/main/packages/kit-docs/src/lib/components/layout/contexts.ts#L224-L256)
