### ISSUE TITLE
Hardcoded background color in CodeFence

### ISSUE THREAD

**Issue by Vilsol** [svelteness/kit-docs#17]
There currently is a hardcoded background for the header of `CodeFence`. This should probably be either made configurable, or changed to completely transparent instead.

https://github.com/svelteness/kit-docs/blob/ed207cf7bf62cef980ce4727af54e3f39d5c0198/packages/kit-docs/src/lib/kit-docs/block/CodeFence.svelte#L84

**Comment by mihar-22** [comment]
Thanks fixed. The following CSS vars should do it:

`--kd-code-fence-bg`
`--kd-code-fence-top-bar-bg`
