### ISSUE TITLE
Dark theme not loading initially

### ISSUE THREAD

**Issue by Myrmod** [svelteness/kit-docs#20]
On version 0.20.0 the dark theme is not applied, if I reload the page.

https://svelte-babylon.netlify.app/docs/introduction/getting-started#creating-a-project

The mode is correctly being set in the localStorage

**Comment by mihar-22** [comment]
I don't see the color scheme script in your `<head>` tag. Add the following to `src/app.html` inside the `<head>`:

```html
<script>
  const key = 'svelteness::color-scheme';
  const scheme = localStorage[key];
  const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
  if (scheme === 'dark' || (scheme !== 'light' && prefersDark)) {
    document.documentElement.classList.add('dark');
  } else {
    document.documentElement.classList.remove('dark');
  }
</script>
```

**Comment by Myrmod** [comment]
Ah yes this should work, but wouldn't it be better to place this code directly in an `onMount` function of maybe https://github.com/svelteness/kit-docs/blob/main/packages/kit-docs/src/lib/components/layout/KitDocs.svelte?

**Comment by mihar-22** [comment]
If you do that the color will flicker from light theme to dark and look odd. The theme has to be set before anything is rendered.

**Comment by Myrmod** [comment]
Makes sense, thanks
