### ISSUE TITLE
Exposing tailwind?

### ISSUE THREAD

**Issue by kelvinsjk** [svelteness/kit-docs#21]
It seems like kit-docs is using tailwind under the hood. 

Is it be possible to expose it so that custom svelte components get tailwind classes support out of the box (and we are able to add tailwind plugins like using markdown-it plugins via the `configureParser` option in `kitDocsPlugin`)? 

Or is it something we should configure on top of kit-docs?

P.S.: Love the project, keep up the great work.

**Comment by mihar-22** [comment]
Hey @kelvinsjk!

When you say expose it what you do you mean exactly? You can pull the `tailwind.config.cjs` file into your own config and re-export it like so:

```js
// tailwind.config.cjs

const config = require('@svelteness/kit-docs/tailwind.config.cjs');

export default {
  ...config,
  content: [
    "src/**/*.svelte", 
    "./node_modules/@svelteness/kit-docs/client/kit-docs/**/*.svelte",
    // Add this if you're using the default theme.
    "'./node_modules/@svelteness/kit-docs/client/**/*.svelte'"
  ]
};
```
Make sure to remove this following lines from your main layout file:

```diff
- import '@svelteness/kit-docs/client/styles/normalize.css';
- import '@svelteness/kit-docs/client/styles/theme.css';
```
Docs mentions this at the following links:

- https://kit-docs.svelteness.dev/docs/getting-started/quickstart#tailwind
- https://kit-docs.svelteness.dev/docs/default-layout/installation#tailwind

Did I misunderstand the question?
