### ISSUE TITLE
[feature] i18n multilanguage support 

### ISSUE THREAD

**Issue by Elliott-Green** [svelteness/kit-docs#26]
I'd like to add multi-lang support using kit-docs.
Is this a feature you'd see value in adding?

**Comment by stephane-klein** [comment]
@Elliott-Green I also look for `i18n` feature.

What did you close this issue?

**Comment by mihar-22** [comment]
Added :)

- https://kit-docs.svelteness.dev/docs/default-layout/configuration#language-i18n
- https://github.com/svelteness/kit-docs/blob/main/packages/kit-docs/src/lib/components/layout/contexts.ts#L253-L287

**Comment by stephane-klein** [comment]
@mihar-22 thank

I had seen this feature, but I look for something like:

![Capture d’écran du 2022-07-02 11-54-14](https://user-images.githubusercontent.com/54498080/176996226-35403e09-a286-4595-8c0e-2462d946ef53.png)

This feature is implemented in `kit-docs`?

**Comment by mihar-22** [comment]
Ah sorry @stephane-klein I haven't implemented nav dropdown menus. You could create your own and insert it via slots:

- https://kit-docs.svelteness.dev/docs/default-layout/configuration#slots

I recommend placing each language in it's own directory :

- routes
  - docs
    - en
      - introduction.md
    - fr
      - introduction.md
    - ...
