### ISSUE TITLE
kit-docs isn't powered by SvelteKit? What is the rational?

### ISSUE THREAD

**Issue by stephane-klein** [svelteness/kit-docs#44]
From the [`package.json`](https://github.com/svelteness/kit-docs/blob/main/package.json) content, it seems that `kit-docs` is not powered by [SvelteKit](https://github.com/sveltejs/kit). Is this correct?

If yes, had the use of `SvelteKit` been considered?  
If yes, why this solution was not chosen?

I ask myself this question, because I think that the `SvelteKit` could have been interesting for `kit-docs` :thinking:

**Comment by grbd** [comment]
I think it is, it's just setup as a workspace so you need to look at the directories underneath the root.
If you look at https://github.com/svelteness/kit-docs/tree/main/demo the package.json in there you'll see sveltekit in use

**Comment by stephane-klein** [comment]
@grbd thanks

I see also SvelteKit [here](https://github.com/svelteness/kit-docs/blob/e4b20bc1d9eb4e2898def10fc583f0bc495f60ef/packages/create-kit-docs/bin/create-kit-docs.js#L96).

I close this issue :+1:
