### ISSUE TITLE
Cannot find package $app

### ISSUE THREAD

**Issue by MichaelBrunn3r** [svelteness/kit-docs#52]
Fresh install with these commands:
```bash
npm init @svelteness/kit-docs docs
> Skeleton project
> Typescript
> eslint
cd docs
pnpm i
pnpm dev
```

Yields this error:
```bash
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '$app' imported from ...\node_modules\.pnpm\@svelteness+kit-docs@0.23.0_svelte@3.49.0\node_modules\@svelteness\kit-docs\client\polyfills\focus-visible.js
    at new NodeError (node:internal/errors:388:5)
    at packageResolve (node:internal/modules/esm/resolve:910:9)
    at moduleResolve (node:internal/modules/esm/resolve:959:20)
    at defaultResolve (node:internal/modules/esm/resolve:1174:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:605:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)
    at link (node:internal/modules/esm/module_job:78:36)
```

The culprit:
```
// @svelteness/kit-docs/client/polyfills/focus-visible.js
import { browser } from '$app/env';
```

`$app` would lead me to believe this is a missing alias?

**Comment by stephane-klein** [comment]
@MichaelBrunn3r same error for me 😐

**Comment by stephane-klein** [comment]
@MichaelBrunn3r I think that this bug come from https://github.com/sveltejs/kit/pull/5005, the SvelteKit upgrade from Vite 2 to 3.

In short term, I propose to pin Vite version [here](https://github.com/svelteness/kit-docs/blob/ce4d7e1f645cf149fe46e2b80df22330a2e3ce74/packages/create-kit-docs/bin/create-kit-docs.js#L113) (See also [this comment](https://github.com/svelteness/kit-docs/issues/50#issuecomment-1182843461)).



cc @mihar-22

**Comment by stephane-klein** [comment]
> @MichaelBrunn3r I think that this bug come from [sveltejs/kit#5005](https://github.com/sveltejs/kit/pull/5005), the SvelteKit upgrade from Vite 2 to 3.
> 
> In short term, I propose to pin Vite version [here](https://github.com/svelteness/kit-docs/blob/ce4d7e1f645cf149fe46e2b80df22330a2e3ce74/packages/create-kit-docs/bin/create-kit-docs.js#L113) (see also [this comment](https://github.com/svelteness/kit-docs/issues/50#issuecomment-1182843461)).

Can be fixed by https://github.com/svelteness/kit-docs/pull/56

**Comment by mihar-22** [comment]
Should be resolved now on latest.
