### ISSUE TITLE
Extra "+page" included in the URL with sidebar navigation

### ISSUE THREAD

**Issue by 2394425147** [svelteness/kit-docs#80]
## Issue

In the latest version (^1.1.1), using the sidebar for navigation currently appends a `+page` to the destination URL

![image](https://user-images.githubusercontent.com/39264547/222457173-d90800f8-6b44-41fa-9a4b-3a4bc2a20b93.png)

## Reproduction

- Perform `npm init @svelteness/kit-docs ./` in an empty folder
- `pnpm install` all the dependencies
- Remove `default: true,` from `svelte.config.js` (throws an error before building for the first time, since `.svelte-kit/` doesn't exist yet)
- Run `npm run dev -- --open`
- Click on `Documentation` in the navbar
- Click on any page title in the sidebar
- There should be a 404 error showing up in the documentation view

This also happened when I tried to manually set the project up. I thought there might be a config parameter I'm missing somewhere that excluded the `.md` files, but this might also just be an issue with route handling in the sidebar, since the `docs/+page.js` redirects to the proper page just fine.

Thanks!

**Comment by gdagosto** [comment]
I'm facing the same issue. 

- Tried to use the quick install, lib is adding +page at the end of every URL and pages are 404.

- Tried running the demo, same issue.

- Tried copying the app that's running on the website, extracted it from this repo, still the same issue.


I've managed to write a small sidebar handler to fix it, but then the sidebar doesn't show the selected current page, and the previous and next buttons also don't work.

```js
import { createSidebarRequestHandler } from "@svelteness/kit-docs/node";

export const GET = createSidebarRequestHandler({
  resolveSlug: (data) => "/" + data.cleanDirname,
});
```

**Comment by mihar-22** [comment]
I think it should work just fine, there might additional paths in the markdown plugins but I'll have to review that later. Looks good to me, thanks!
