### ISSUE TITLE
`npm init` needs to be updated

### ISSUE THREAD

**Issue by microdou** [svelteness/kit-docs#9]
The following command from [Quick Installation](https://kit-docs.svelteness.dev/docs/getting-started/quickstart#quick-installation) results in a code base that hasn't been updated since `v0.3.3`

```
npm init @svelteness/kit-docs mydocs
```

**Comment by mihar-22** [comment]
I just tested it and it returned the latest with no issues.

**Comment by mihar-22** [comment]
It's on version [`0.7.0`](https://github.com/svelteness/kit-docs/blob/main/packages/create-kit-docs/package.json#L3) the same as the `kit-docs` package.

**Comment by mihar-22** [comment]
Probably cache issue. Try running it like so: `npm init @svelteness/kit-docs@latest mydocs`

**Comment by microdou** [comment]
Oh yes, it was an npm cache issue!

`@latest` is the magic word. Probably necessary to be included in your tutorial :wink:
