### ISSUE TITLE
QuickStart Outdated?

### ISSUE THREAD

**Issue by ckartik** [svelteness/kit-docs#91]
There seems to be a slight issue with the Quickstart guide. Doing a fresh install leads to this issue:

```
> mydocs@0.0.1 dev
> vite dev --open

▲ [WARNING] Cannot find base config file "./.svelte-kit/tsconfig.json" [tsconfig.json]

    jsconfig.json:2:12:
      2 │   "extends": "./.svelte-kit/tsconfig.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error when starting dev server:
Error: Unexpected option config.kit.prerender.default
    ```
    
    It's searching for a tsconfig.json file that doesn't get created

**Comment by CaptainCodeman** [comment]
The warning is how SvelteKit works - the file is created in the `.svelte-kit` folder the first time you run dev (or sync). You can ignore that.

The error with the `config.kit.prerender.default` option is a leftover from an earlier, pre-release, version of SvelteKit. You can delete that entry from the svelte.config.js file.
